version: "3.7"

services:
  api:
    image: api
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:3000"
    depends_on:
      - minio
  
  minio:
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data

volumes:
  minio_data: